# Generated by Django 4.0.5 on 2022-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('occupantname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=150)),
                ('daystospend', models.CharField(max_length=150)),
                ('startdate', models.CharField(max_length=150)),
                ('enddate', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'bookrecord',
            },
        ),
    ]
